### ISSUE TITLE
Uncaught ReferenceError: callback is not defined

### ISSUE THREAD

**Issue by kaspar-allenbach** [jonnyhaynes/inline-svg#11]
If I use your plugin like this:

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="/node_modules/inline-svg/dist/inlineSVG.min.js"></script>
  <script>
    inlineSVG.init({
      svgSelector: 'img.svg', // the class attached to all images that should be inlined
      initClass: 'js-inlinesvg', // class added to <html>
      storeResults: false // should the results be stored in localStorage
    }, callback);
  </script> 
```

I receive: 

> Uncaught ReferenceError: callback is not defined

Why? If I remove the callback it works. Is this really needed?

**Comment by oliverfarrell** [comment]
@kaspar-allenbach That's just an example. You haven't defined callback so it will always fail. You might want to execute another script once all the SVGs have been inlined and that's what the callback allows you to do. There's no problem with the plugin.
