### ISSUE TITLE
Aria labelledby not pointing to correct value

### ISSUE THREAD

**Issue by hidanielle** [jonnyhaynes/inline-svg#17]
`aria-labelledby` should point to an ID, but instead it is pointing to the `title` tag. This leads to a broken aria reference.

Additionally, `aria-labelledby` shouldn't be added if no `alt` attribute is present. Can consider adding `role="presentation"` and `aria-hidden="true"` in cases where no `alt` is present. As this tells screen readers to ignore it, similar to when an empty `alt` is present on `img` tags

**Comment by aayushsapkota** [comment]
I came across the same issue too. Is this going to be fixed anytime soon?

**Comment by jpsantos7** [comment]
+1 – I'm also getting this in my aXe audits. Any news on this issue?

Great work on this @jonnyhaynes btw!

**Comment by subfighter3** [comment]
Thank you @jpsantos7 !!
Amazing job!
