### ISSUE TITLE
Support for SVGs stored on AWS

### ISSUE THREAD

**Issue by l3iodeez** [jonnyhaynes/inline-svg#5]
Hello!
I am trying to find a solution to allow inline insertion of SVG graphics which are stored on a AWS S3 process. I am able to get inline-svg working but if my img tag refers to the AWS URL then the SVG is not inserted inline, its left as an image tag (the svg is visible, just not inline). Is there any way to get inline-svg.js to work with files stored on AWS?

**Comment by oliverfarrell** [comment]
@l3iodeez Gotcha. It's likely to be an issue with your AWS configuration. By default AWS isn't configured for **Cross-Origin Resource Sharing (CORS)** – basically, it doesn't allow GET requests – which is what the script does to grab the contents of the SVG. If you look in your browsers developer tools you'll probably have a few console errors, something along the lines of **No 'Access-Control-Allow-Origin' header is present on the requested resource.**

The [AWS Docs](http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) might help resolve this issue for you, but do let me know if it doesn't.

**Comment by l3iodeez** [comment]
That was it. Everything seems to be working properly after configuring CORS in AWS.  Thanks!
